version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: reverseproxy
  udagram-feed:
    build:
      context: ./udagram-api-feed
    image: jmanzanog/udagramfeed
  udagram-user:
    build:
      context: ./udagram-api-user
    image: jmanzanog/udagramuser
  frontend:
    build:
      context: ./udagram-frontend
    image: jmanzanog/udagram-frontend